project:add.o print.o main.o delete.o 
	cc -o project add.o print.o main.o delete.o 
add.o:add.c
	cc -c add.c -o add.o
print.o:print.c
	cc -c print.c -o print.o
main.o:main.c
	cc -c main.c -o main.o
delete.o:delete.c
	cc -c delete.c -o delete.o


